### ISSUE TITLE
[findrepe][0.10.0]exception parsing some wrong options

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#23]
```
when executing

findrepe -w

the following exception is thrown

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
    at com.softenido.cafe.util.options.StringOption.parseShort(StringOption.java:117)
    at com.softenido.cafe.util.options.OptionParser.parseShort(OptionParser.java:152)
    at com.softenido.cafe.util.options.OptionParser.parse(OptionParser.java:100)
    at com.softenido.findrepe.FindRepeMain.main(FindRepeMain.java:239)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 20 Oct 2010 at 10:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 20 Oct 2010 at 10:40
- Changed title: **[findrepe][0.10.0]exception parsing some wrong options**

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 23 Oct 2010 at 9:34
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 23 Oct 2010 at 9:53
- Changed state: **Fixed**
