### ISSUE TITLE
[wifix][0.2.3]Keep Connection throws an exception when screen is rotated

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#27]
```
steps to reproduce the problem

1. check on "Keep Connection"
2. rotate screen
3. ckeck off "Keep Connection"

Then you get an exception.

java.lang.RuntimeException: WifiLock under-locked WifiLock
at android.net.wifi.WifiManager$WifiLock.release(WifiManager.java:1131)
at com.softenido.wifix.Wifix$3.onClick(Wifix.java:72)
at android.view.View.performClick(View.java:2461)
at android.widget.CompoundButton.performClick(CompoundButton.java:99)
at android.view.View$PerformClick.run(View.java:8890)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4632)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 24 Nov 2011 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
fixed v0.2.4
```

Original comment by `flik...@gmail.com` on 25 Nov 2011 at 7:36
- Changed state: **Fixed**
