### ISSUE TITLE
[wifix][0.3.0] com.softenido.wifix/.Wifix ANR keyDispatchingTimedOut

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#28]
```
Activivy com.softenido.wifix/.Wifix blocked.

Cause: ANR keyDispatchingTimedOut

DALVIK THREADS:
"main" prio=5 tid=1 NATIVE
  | group="main" sCount=1 dsCount=0 s=N obj=0x400208b8 self=0xcd68
  | sysTid=9184 nice=0 sched=0/0 cgrp=unknown handle=-1345026000
  at android.os.BinderProxy.transact(Native Method)
  at android.net.wifi.IWifiManager$Stub$Proxy.reassociate(IWifiManager.java:576)
  at android.net.wifi.WifiManager.reassociate(WifiManager.java:533)
  at com.softenido.wifix.f.onClick((null):-1)
  at android.view.View.performClick(View.java:2408)
  at android.view.View$PerformClick.run(View.java:8816)
  at android.os.Handler.handleCallback(Handler.java:587)
  at android.os.Handler.dispatchMessage(Handler.java:92)
  at android.os.Looper.loop(Looper.java:123)
  at android.app.ActivityThread.main(ActivityThread.java:4627)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:521)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:876)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
  at dalvik.system.NativeStart.main(Native Method)

"Thread-19" prio=5 tid=14 NATIVE
  | group="main" sCount=1 dsCount=0 s=N obj=0x4519a0f0 self=0x1ddb10
  | sysTid=9251 nice=0 sched=0/0 cgrp=unknown handle=1917888
  at dalvik.system.NativeStart.run(Native Method)

"Thread-16" prio=5 tid=13 NATIVE
  | group="main" sCount=1 dsCount=0 s=N obj=0x4515c9a8 self=0x1c2b88
  | sysTid=9200 nice=0 sched=0/0 cgrp=unknown handle=1826288
  at dalvik.system.NativeStart.run(Native Method)

"Thread-14" prio=5 tid=12 NATIVE
  | group="main" sCount=1 dsCount=0 s=N obj=0x451257a0 self=0x195120
  | sysTid=9197 nice=0 sched=0/0 cgrp=unknown handle=1175856
  at dalvik.system.NativeStart.run(Native Method)

"DNS resolver" prio=5 tid=10 WAIT
  | group="main" sCount=1 dsCount=0 s=N obj=0x45156730 self=0x186c30
  | sysTid=9196 nice=1 sched=0/0 cgrp=unknown handle=1601648
  at java.lang.Object.wait(Native Method)
  - waiting on <0x45132e08> (a java.lang.Object)
  at java.lang.Object.wait(Object.java:288)
  at android.webkit.DnsResolver$1.run(DnsResolver.java:111)
  at java.lang.Thread.run(Thread.java:1096)

"Thread-12" prio=5 tid=11 NATIVE
  | group="main" sCount=1 dsCount=0 s=N obj=0x450be908 self=0x1698f8
  | sysTid=9195 nice=0 sched=0/0 cgrp=unknown handle=1478816
  at dalvik.system.NativeStart.run(Native Method)

"CookieSyncManager" prio=5 tid=9 TIMED_WAIT
  | group="main" sCount=1 dsCount=0 s=N obj=0x4516c438 self=0x140038
  | sysTid=9193 nice=10 sched=0/0 cgrp=unknown handle=1252200
  at java.lang.Object.wait(Native Method)
  - waiting on <0x4512c568> (a android.os.MessageQueue)
  at java.lang.Object.wait(Object.java:326)
  at android.os.MessageQueue.next(MessageQueue.java:142)
  at android.os.Looper.loop(Looper.java:110)
  at android.webkit.WebSyncManager.run(WebSyncManager.java:90)
  at java.lang.Thread.run(Thread.java:1096)

"WebViewCoreThread" prio=5 tid=8 WAIT
  | group="main" sCount=1 dsCount=0 s=N obj=0x451754f8 self=0x12e058
  | sysTid=9191 nice=0 sched=0/0 cgrp=unknown handle=962224
  at java.lang.Object.wait(Native Method)
  - waiting on <0x451757e0> (a android.os.MessageQueue)
  at java.lang.Object.wait(Object.java:288)
  at android.os.MessageQueue.next(MessageQueue.java:146)
  at android.os.Looper.loop(Looper.java:110)
  at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:626)
  at java.lang.Thread.run(Thread.java:1096)

"Binder Thread #2" prio=5 tid=7 NATIVE
  | group="main" sCount=1 dsCount=0 s=N obj=0x450e90e8 self=0xee270
  | sysTid=9190 nice=0 sched=0/0 cgrp=unknown handle=532600
  at dalvik.system.NativeStart.run(Native Method)

"Binder Thread #1" prio=5 tid=6 NATIVE
  | group="main" sCount=1 dsCount=0 s=N obj=0x450e9028 self=0xed590
  | sysTid=9189 nice=0 sched=0/0 cgrp=unknown handle=532536
  at dalvik.system.NativeStart.run(Native Method)

"Compiler" daemon prio=5 tid=5 VMWAIT
  | group="system" sCount=1 dsCount=0 s=N obj=0x450ac348 self=0xe9be8
  | sysTid=9188 nice=0 sched=0/0 cgrp=unknown handle=957352
  at dalvik.system.NativeStart.run(Native Method)

"JDWP" daemon prio=5 tid=4 VMWAIT
  | group="system" sCount=1 dsCount=0 s=N obj=0x450ac2a0 self=0xe9180
  | sysTid=9187 nice=0 sched=0/0 cgrp=unknown handle=954688
  at dalvik.system.NativeStart.run(Native Method)

"Signal Catcher" daemon prio=5 tid=3 RUNNABLE
  | group="system" sCount=0 dsCount=0 s=N obj=0x450ac1e8 self=0xe65d0
  | sysTid=9186 nice=0 sched=0/0 cgrp=unknown handle=943504
  at dalvik.system.NativeStart.run(Native Method)

"HeapWorker" daemon prio=5 tid=2 VMWAIT
  | group="system" sCount=1 dsCount=0 s=N obj=0x438f5e60 self=0xe5b60
  | sysTid=9185 nice=0 sched=0/0 cgrp=unknown handle=940832
  at dalvik.system.NativeStart.run(Native Method)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 6 Jan 2012 at 9:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 14 Oct 2012 at 12:15
- Changed state: **Fixed**
