### ISSUE TITLE
[examples][0.3.0] Error pushing button "port 9999" in "Text to Speech" option.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#29]
```
What steps will reproduce the problem?

1. With no wifi, GPRS or 3G connection open "Text to Speech"
2. Push button "port 9999"
3. then you get an error

The stack trace is the following:

java.lang.NullPointerException
at com.softenido.examples.SpeechActivity.a(Unknown Source)
at com.softenido.examples.SpeechActivity.a(Unknown Source)
at com.softenido.examples.f.onClick(Unknown Source)
at android.view.View.performClick(View.java:2485)
at android.widget.CompoundButton.performClick(CompoundButton.java:99)
at android.view.View$PerformClick.run(View.java:9080)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3695)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 27 Jan 2012 at 6:20

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 27 Jan 2012 at 6:22
- Changed title: **[examples][0.3.0] Error pushing button "port 9999" in "Text to Speech" option.**

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 27 Jan 2012 at 6:22
- Added labels: **0.3.0**, **examples**

**Comment by GoogleCodeExporter** [comment]
```
efc94efd11f462db84d846ed751b4f10657cd971
```

Original comment by `flik...@gmail.com` on 27 Jan 2012 at 7:12
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 27 Jan 2012 at 7:12
- Changed state: **Fixed**
