### ISSUE TITLE
[findrepe][0.1.1] Exception java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#3]
```
What steps will reproduce the problem?

1. Run the following commandline in opensolaris

java -jar findrepe-0.1.1/FindRepe.jar /usr/

2. After a while waiting you get the following exception

Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2882)
    at
java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:572)
    at java.lang.StringBuilder.append(StringBuilder.java:203)
    at java.io.UnixFileSystem.resolve(UnixFileSystem.java:93)
    at java.io.File.<init>(File.java:207)
    at java.io.File.listFiles(File.java:1056)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:173)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:181)
    at com.softenido.cafe.io.ForEachFile.run(ForEachFile.java:151)
    at com.softenido.cafe.io.ForEachFileQueue.run(ForEachFileQueue.java:102)
    at
com.softenido.findrepe.ForEachArrayFileQueue.run(ForEachArrayFileQueue.java:87)
    at java.lang.Thread.run(Thread.java:619)

I think it might be a ciclyc link (link shouldn't be followed by default
unless the apropiated option is added, ciclyc link should be also detected).

```

Original issue reported on code.google.com by `flik...@gmail.com` on 9 Apr 2009 at 3:02

**Comment by GoogleCodeExporter** [comment]
```
fixed at version 0.3.0
```

Original comment by `flik...@gmail.com` on 2 May 2009 at 3:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 2 May 2009 at 3:57
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 2 May 2009 at 3:58
- Changed state: **Verified**
