### ISSUE TITLE
[audible][0.4.0]NullPointerException in AudibleMain.n()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#34]
```
Crash: 
Exception class: java.lang.NullPointerException
Source method: AudibleMain.n()

Platforms: OTHER

Stack traces:

java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.softenido.audible/com.softenido.audible.AudibleMain}: 
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1970)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995)
at android.app.ActivityThread.access$600(ActivityThread.java:128)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4514)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.softenido.audible.AudibleMain.n(Unknown Source)
at com.softenido.audible.AudibleMain.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934)
... 11 more

retraced:

java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.softenido.audible/com.softenido.audible.AudibleMain}: 
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1970)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995)
at android.app.ActivityThread.access$600(ActivityThread.java:128)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4514)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.softenido.audible.AudibleMain.void loadHeadAndBody()(Unknown Source)
at com.softenido.audible.AudibleMain.void onCreate(android.os.Bundle)(Unknown 
Source)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934)
... 11 more
```

Original issue reported on code.google.com by `flik...@gmail.com` on 9 Dec 2012 at 4:01

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 9 Dec 2012 at 4:12
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
User Message: всо. виделит

Tranlation: ???

```

Original comment by `flik...@gmail.com` on 9 Dec 2012 at 4:30
