### ISSUE TITLE
[audible][0.4.1] java.lang.IllegalArgumentException in android.os.Parcel.readException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#36]
```
java.lang.IllegalArgumentException: Invalid int: "OS"
at android.os.Parcel.readException(Parcel.java:1429)
at android.os.Parcel.readException(Parcel.java:1379)
at 
android.speech.tts.ITextToSpeechService$Stub$Proxy.isLanguageAvailable(ITextToSp
eechService.java:482)
at android.speech.tts.TextToSpeech$10.run(TextToSpeech.java:1084)
at android.speech.tts.TextToSpeech$10.run(TextToSpeech.java:1081)
at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:1331)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:570)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:561)
at android.speech.tts.TextToSpeech.isLanguageAvailable(TextToSpeech.java:1081)
at com.softenido.cafedroid.e.k.b(Unknown Source)
at com.softenido.cafedroid.e.k.a(Unknown Source)
at com.softenido.audible.l.a(Unknown Source)
at com.softenido.cafedroid.e.k.onInit(Unknown Source)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:640)
at android.speech.tts.TextToSpeech.access$1000(TextToSpeech.java:52)
at 
android.speech.tts.TextToSpeech$Connection.onServiceConnected(TextToSpeech.java:
1298)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1097)
at 
android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1114)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method)

```

Original issue reported on code.google.com by `flik...@gmail.com` on 29 Dec 2012 at 11:40

**Comment by GoogleCodeExporter** [comment]
```
retraced:

java.lang.IllegalArgumentException: Invalid int: "OS"
at android.os.Parcel.readException(Parcel.java:1429)
at android.os.Parcel.readException(Parcel.java:1379)
at 
android.speech.tts.ITextToSpeechService$Stub$Proxy.isLanguageAvailable(ITextToSp
eechService.java:482)
at android.speech.tts.TextToSpeech$10.run(TextToSpeech.java:1084)
at android.speech.tts.TextToSpeech$10.run(TextToSpeech.java:1081)
at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:1331)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:570)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:561)
at android.speech.tts.TextToSpeech.isLanguageAvailable(TextToSpeech.java:1081)
at com.softenido.cafedroid.speech.SpeechSpeaker.void install()(Unknown Source)
                                                int isLanguageAvailable(java.util.Locale)
                                                void unregisterOnSpeakingListener(com.softenido.cafedroid.speech.SpeechSpeaker$OnSpeakingListener)
                                                void adjustVolume(int,int)
at com.softenido.cafedroid.speech.SpeechSpeaker.boolean start()(Unknown Source)
                                                void onActivityResult(int,int,android.content.Intent)
                                                int setLanguage(java.util.Locale)
                                                boolean waitForStarted(int)
                                                java.util.Locale[] getAvailableLocales(java.util.Locale[])
                                                java.lang.String speak(java.lang.String,boolean,boolean)
                                                java.lang.String speak(java.lang.String,boolean,boolean,java.lang.String)
                                                void registerOnSpeakingListener(com.softenido.cafedroid.speech.SpeechSpeaker$OnSpeakingListener)
                                                void setVolume(int,int)
at com.softenido.audible.AudibleMain$2.void onSpeekerInstallNeeded()(Unknown 
Source)
                                       void onSpeekerInitied(boolean)
at com.softenido.cafedroid.speech.SpeechSpeaker.void onInit(int)(Unknown Source)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:640)
at android.speech.tts.TextToSpeech.access$1000(TextToSpeech.java:52)
at 
android.speech.tts.TextToSpeech$Connection.onServiceConnected(TextToSpeech.java:
1298)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1097)
at 
android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1114)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method)

```

Original comment by `flik...@gmail.com` on 29 Dec 2012 at 11:41

**Comment by GoogleCodeExporter** [comment]
```
This error was reported for Galaxy Note Android 4.1.1
```

Original comment by `friedger@gmail.com` on 6 Jan 2013 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
@friedger, can you give me some more info?

- Speech synthesizer
- installed voices
- Default language
- it was activated "detect language"?

additional info will be welcomed
```

Original comment by `flik...@gmail.com` on 6 Jan 2013 at 9:07

**Comment by GoogleCodeExporter** [comment]
```
Actually, it was a Galaxy Tab

Samsung TTS
French (Marie)

With Google TTS the error does not occur....
```

Original comment by `friedger@gmail.com` on 6 Jan 2013 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Can you give me a little piece of text that fails? Maybe all but to be shure.
```

Original comment by `flik...@gmail.com` on 6 Jan 2013 at 10:51

**Comment by GoogleCodeExporter** [comment]
```
The error occurred on a friend's device. Sorry, not.
I have the same problem with Plaphoons for Android.
```

Original comment by `friedger@gmail.com` on 6 Jan 2013 at 10:56

**Comment by GoogleCodeExporter** [comment]
```
Ok, I'll try to reproduce it anyway.
```

Original comment by `flik...@gmail.com` on 6 Jan 2013 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
This is probably to late for you guys but for those who are still looking for a 
solution:

I was able to pin-point this error to when you pass the locale "en_US_POSIX" to 
the isLanguageAvailable(locale) method.

What I did is excluded this locale from the list.
```

Original comment by `miguel16...@gmail.com` on 20 Jun 2014 at 6:59
