### ISSUE TITLE
[audible][0.4.1] java.lang.NullPointerException in android.app.ActivityThread.handleStopActivity

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#37]
```
java.lang.NullPointerException
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:2476)
at android.app.ActivityThread.access$1800(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:952)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 29 Dec 2012 at 11:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 29 Dec 2012 at 11:55
- Added labels: **Crashes**

**Comment by GoogleCodeExporter** [comment]
```
I saw the same error. (Can't reproduce it though.)
java.lang.NullPointerException
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3455)
    at android.app.ActivityThread.access$2600(ActivityThread.java:125)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2050)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4627)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at dalvik.system.NativeStart.main(Native Method)

I checked the froyo source(the device was froyo)
and found that it happens at 'r.activity.mConfigChangeFlags |= configChanges;'
http://androidxref.com/2.2.3/xref/frameworks/base/core/java/android/app/Activity
Thread.java#3455

r or activity must be null but I don't know how this happens.

This also happens in gingerbread as well.
```

Original comment by `noranb...@gmail.com` on 11 Mar 2013 at 1:04

**Comment by GoogleCodeExporter** [comment]
```
I really don't know how it happens but maybe activity has been destroyed before 
the event is dispathced. 
```

Original comment by `flik...@gmail.com` on 11 Mar 2013 at 7:18
