### ISSUE TITLE
[audible][0.4.1] ANR keyDispatchingTimedOut in android/com.android.internal.app.ChooserActivity

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#39]
```
DALVIK THREADS:
(mutexes: tll=0 tsl=0 tscl=0 ghl=0 hwl=0 hwll=0)
"main" prio=5 tid=1 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x400221a8 self=0xcec8
| sysTid=21611 nice=0 sched=0/0 cgrp=default handle=-1345006496
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:119)
at android.os.Looper.loop(Looper.java:117)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)

"SpeechPlayer.classify" prio=5 tid=26 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40605b30 self=0x3c1010
| sysTid=21739 nice=0 sched=0/0 cgrp=default handle=4426920
at java.util.regex.Matcher.openImpl(Native Method)
at java.util.regex.Matcher.usePattern(Matcher.java:242)
at java.util.Scanner.setTokenRegion(Scanner.java:2024)
at java.util.Scanner.hasNext(Scanner.java:581)
at java.util.Scanner.hasNext(Scanner.java:559)
at com.softenido.a.f.a.c.a((null):-1)
at com.softenido.a.f.a.b.a((null):-1)
at com.softenido.a.f.a.c.b((null):-1)
at com.softenido.a.f.a.b.b((null):-1)
at com.softenido.cafedroid.e.c.l((null):-1)
at com.softenido.cafedroid.e.c.c((null):-1)
at com.softenido.cafedroid.e.f.run((null):-1)
at java.lang.Thread.run(Thread.java:1019)

"pool-1-thread-1" prio=5 tid=9 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40595810 self=0x225820
| sysTid=21701 nice=0 sched=0/0 cgrp=default handle=3698520
at java.lang.Object.wait(Native Method)
- waiting on <0x405cb240> (a java.lang.VMThread)
at java.lang.Thread.parkFor(Thread.java:1424)
at java.lang.LangAccessImpl.parkFor(LangAccessImpl.java:48)
at sun.misc.Unsafe.park(Unsafe.java:337)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at 
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Abst
ractQueuedSynchronizer.java:2016)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:411)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1021)
at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1081)
at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)

"http11" prio=5 tid=24 WAIT
| group="main" sCount=1 dsCount=0 obj=0x405576c0 self=0x19ff50
| sysTid=21638 nice=1 sched=0/0 cgrp=default handle=1745712
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http10" prio=5 tid=23 WAIT
| group="main" sCount=1 dsCount=0 obj=0x4057b698 self=0x19fe18
| sysTid=21636 nice=1 sched=0/0 cgrp=default handle=1728640
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http9" prio=5 tid=22 WAIT
| group="main" sCount=1 dsCount=0 obj=0x4057b488 self=0x19fce0
| sysTid=21635 nice=1 sched=0/0 cgrp=default handle=2489360
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http8" prio=5 tid=21 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40549dc8 self=0x25fa80
| sysTid=21634 nice=1 sched=0/0 cgrp=default handle=2024704
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http7" prio=5 tid=20 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40549bb8 self=0x1ee3c8
| sysTid=21633 nice=1 sched=0/0 cgrp=default handle=1744584
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http6" prio=5 tid=19 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40568f20 self=0x2626b8
| sysTid=21632 nice=1 sched=0/0 cgrp=default handle=2500632
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http5" prio=5 tid=18 WAIT
| group="main" sCount=1 dsCount=0 obj=0x4056a290 self=0x2618e0
| sysTid=21631 nice=1 sched=0/0 cgrp=default handle=2497048
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http4" prio=5 tid=17 WAIT
| group="main" sCount=1 dsCount=0 obj=0x4056a020 self=0x260ed8
| sysTid=21630 nice=1 sched=0/0 cgrp=default handle=2494480
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http3" prio=5 tid=16 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40578840 self=0x260510
| sysTid=21629 nice=1 sched=0/0 cgrp=default handle=2488880
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http2" prio=5 tid=15 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40578680 self=0x25f560
| sysTid=21628 nice=1 sched=0/0 cgrp=default handle=2471784
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http1" prio=5 tid=14 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40576d20 self=0x259e00
| sysTid=21627 nice=1 sched=0/0 cgrp=default handle=2298896
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http0" prio=5 tid=13 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40553958 self=0x230918
| sysTid=21626 nice=1 sched=0/0 cgrp=default handle=2302360
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"Thread-16" prio=5 tid=12 TIMED_WAIT
| group="main" sCount=1 dsCount=0 obj=0x40583090 self=0x2374b8
| sysTid=21625 nice=0 sched=0/0 cgrp=default handle=2227712
at java.lang.VMThread.sleep(Native Method)
at java.lang.Thread.sleep(Thread.java:1213)
at java.lang.Thread.sleep(Thread.java:1195)
at com.softenido.audible.ak.run((null):-1)
at java.lang.Thread.run(Thread.java:1019)

"CookieSyncManager" prio=5 tid=11 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40584770 self=0x1f0998
| sysTid=21622 nice=10 sched=0/0 cgrp=bg_non_interactive handle=2034384
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:119)
at android.os.Looper.loop(Looper.java:117)
at android.webkit.WebSyncManager.run(WebSyncManager.java:90)
at android.webkit.CookieSyncManager.run(CookieSyncManager.java:61)
at java.lang.Thread.run(Thread.java:1019)

"WebViewWorkerThread" prio=5 tid=10 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40583d08 self=0x1edc00
| sysTid=21620 nice=1 sched=0/0 cgrp=default handle=2026536
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:119)
at android.os.Looper.loop(Looper.java:117)
at android.os.HandlerThread.run(HandlerThread.java:60)

"WebViewCoreThread" prio=5 tid=8 SUSPENDED
| group="main" sCount=1 dsCount=0 obj=0x40547cf0 self=0x1a76f8
| sysTid=21618 nice=0 sched=0/0 cgrp=default handle=1734704
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:119)
at android.os.Looper.loop(Looper.java:117)
at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:685)
at java.lang.Thread.run(Thread.java:1019)

"Binder Thread #2" prio=5 tid=7 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40514248 self=0x182cb0
| sysTid=21617 nice=0 sched=0/0 cgrp=default handle=1427792
at dalvik.system.NativeStart.run(Native Method)

"Binder Thread #1" prio=5 tid=6 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40514180 self=0x15c6b0
| sysTid=21616 nice=0 sched=0/0 cgrp=default handle=1479520
at dalvik.system.NativeStart.run(Native Method)

"Compiler" daemon prio=5 tid=5 VMWAIT
| group="system" sCount=1 dsCount=0 obj=0x40510d68 self=0x163270
| sysTid=21615 nice=0 sched=0/0 cgrp=default handle=1454640
at dalvik.system.NativeStart.run(Native Method)

"Signal Catcher" daemon prio=5 tid=4 RUNNABLE
| group="system" sCount=0 dsCount=0 obj=0x40510ca8 self=0x97570
| sysTid=21614 nice=0 sched=0/0 cgrp=default handle=619824
at dalvik.system.NativeStart.run(Native Method)

"GC" daemon prio=5 tid=3 VMWAIT
| group="system" sCount=1 dsCount=0 obj=0x40510c00 self=0x96e08
| sysTid=21613 nice=0 sched=0/0 cgrp=default handle=617928
at dalvik.system.NativeStart.run(Native Method)

"HeapWorker" daemon prio=5 tid=2 VMWAIT
| group="system" sCount=1 dsCount=0 obj=0x40510b48 self=0x162fb8
| sysTid=21612 nice=0 sched=0/0 cgrp=default handle=617728
at dalvik.system.NativeStart.run(Native Method)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 29 Dec 2012 at 11:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 29 Dec 2012 at 11:54
- Added labels: **ANR**

**Comment by GoogleCodeExporter** [comment]
```
retraced:

DALVIK THREADS:
(mutexes: tll=0 tsl=0 tscl=0 ghl=0 hwl=0 hwll=0)
"main" prio=5 tid=1 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x400221a8 self=0xcec8
| sysTid=21611 nice=0 sched=0/0 cgrp=default handle=-1345006496
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:119)
at android.os.Looper.loop(Looper.java:117)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)

"SpeechPlayer.classify" prio=5 tid=26 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40605b30 self=0x3c1010
| sysTid=21739 nice=0 sched=0/0 cgrp=default handle=4426920
at java.util.regex.Matcher.openImpl(Native Method)
at java.util.regex.Matcher.usePattern(Matcher.java:242)
at java.util.Scanner.setTokenRegion(Scanner.java:2024)
at java.util.Scanner.hasNext(Scanner.java:581)
at java.util.Scanner.hasNext(Scanner.java:559)
at 
com.softenido.cafecore.statistics.classifier.BaseTextClassifier.com.softenido.ca
fecore.statistics.classifier.Score classify(java.util.Scanner)((null):-1)
                                                                   boolean isLetterOrDigit(int)
                                                                   void load(java.io.InputStream,boolean,java.lang.String[])
at 
com.softenido.cafecore.statistics.classifier.AbstractLanguageClassifier.boolean 
add(java.lang.String[])((null):-1)
                                                                           boolean initialize()
                                                                           boolean initialize(java.lang.String)
                                                                           com.softenido.cafecore.statistics.classifier.Score classify(java.util.Scanner)
                                                                           void setStatusNotifier(com.softenido.cafecore.logging.StatusNotifier)
at 
com.softenido.cafecore.statistics.classifier.BaseTextClassifier.com.softenido.ca
fecore.statistics.classifier.Score classify(java.lang.String)((null):-1)
                                                                   boolean isAsian(int)
at 
com.softenido.cafecore.statistics.classifier.AbstractLanguageClassifier.boolean 
set(java.lang.String[])((null):-1)
                                                                           com.softenido.cafecore.statistics.classifier.Score classify(java.lang.String)
                                                                           boolean initializeLoop()
at com.softenido.cafedroid.speech.SpeechPlayer.void classify()((null):-1)
at com.softenido.cafedroid.speech.SpeechPlayer.void pause()((null):-1)
                                               void setLowerCase(boolean)
                                               void access$200(com.softenido.cafedroid.speech.SpeechPlayer)
at com.softenido.cafedroid.speech.SpeechPlayer$3.void run()((null):-1)
at java.lang.Thread.run(Thread.java:1019)

"pool-1-thread-1" prio=5 tid=9 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40595810 self=0x225820
| sysTid=21701 nice=0 sched=0/0 cgrp=default handle=3698520
at java.lang.Object.wait(Native Method)
- waiting on <0x405cb240> (a java.lang.VMThread)
at java.lang.Thread.parkFor(Thread.java:1424)
at java.lang.LangAccessImpl.parkFor(LangAccessImpl.java:48)
at sun.misc.Unsafe.park(Unsafe.java:337)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at 
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Abst
ractQueuedSynchronizer.java:2016)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:411)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1021)
at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1081)
at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)

"http11" prio=5 tid=24 WAIT
| group="main" sCount=1 dsCount=0 obj=0x405576c0 self=0x19ff50
| sysTid=21638 nice=1 sched=0/0 cgrp=default handle=1745712
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http10" prio=5 tid=23 WAIT
| group="main" sCount=1 dsCount=0 obj=0x4057b698 self=0x19fe18
| sysTid=21636 nice=1 sched=0/0 cgrp=default handle=1728640
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http9" prio=5 tid=22 WAIT
| group="main" sCount=1 dsCount=0 obj=0x4057b488 self=0x19fce0
| sysTid=21635 nice=1 sched=0/0 cgrp=default handle=2489360
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http8" prio=5 tid=21 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40549dc8 self=0x25fa80
| sysTid=21634 nice=1 sched=0/0 cgrp=default handle=2024704
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http7" prio=5 tid=20 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40549bb8 self=0x1ee3c8
| sysTid=21633 nice=1 sched=0/0 cgrp=default handle=1744584
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http6" prio=5 tid=19 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40568f20 self=0x2626b8
| sysTid=21632 nice=1 sched=0/0 cgrp=default handle=2500632
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http5" prio=5 tid=18 WAIT
| group="main" sCount=1 dsCount=0 obj=0x4056a290 self=0x2618e0
| sysTid=21631 nice=1 sched=0/0 cgrp=default handle=2497048
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http4" prio=5 tid=17 WAIT
| group="main" sCount=1 dsCount=0 obj=0x4056a020 self=0x260ed8
| sysTid=21630 nice=1 sched=0/0 cgrp=default handle=2494480
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http3" prio=5 tid=16 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40578840 self=0x260510
| sysTid=21629 nice=1 sched=0/0 cgrp=default handle=2488880
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http2" prio=5 tid=15 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40578680 self=0x25f560
| sysTid=21628 nice=1 sched=0/0 cgrp=default handle=2471784
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http1" prio=5 tid=14 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40576d20 self=0x259e00
| sysTid=21627 nice=1 sched=0/0 cgrp=default handle=2298896
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"http0" prio=5 tid=13 WAIT
| group="main" sCount=1 dsCount=0 obj=0x40553958 self=0x230918
| sysTid=21626 nice=1 sched=0/0 cgrp=default handle=2302360
at java.lang.Object.wait(Native Method)
- waiting on <0x4055a490> (a android.net.http.RequestQueue)
at java.lang.Object.wait(Object.java:358)
at android.net.http.ConnectionThread.run(ConnectionThread.java:98)

"Thread-16" prio=5 tid=12 TIMED_WAIT
| group="main" sCount=1 dsCount=0 obj=0x40583090 self=0x2374b8
| sysTid=21625 nice=0 sched=0/0 cgrp=default handle=2227712
at java.lang.VMThread.sleep(Native Method)
at java.lang.Thread.sleep(Thread.java:1213)
at java.lang.Thread.sleep(Thread.java:1195)
at com.softenido.audible.KeepAudibleLoadService$3.void run()((null):-1)
at java.lang.Thread.run(Thread.java:1019)

"CookieSyncManager" prio=5 tid=11 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40584770 self=0x1f0998
| sysTid=21622 nice=10 sched=0/0 cgrp=bg_non_interactive handle=2034384
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:119)
at android.os.Looper.loop(Looper.java:117)
at android.webkit.WebSyncManager.run(WebSyncManager.java:90)
at android.webkit.CookieSyncManager.run(CookieSyncManager.java:61)
at java.lang.Thread.run(Thread.java:1019)

"WebViewWorkerThread" prio=5 tid=10 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40583d08 self=0x1edc00
| sysTid=21620 nice=1 sched=0/0 cgrp=default handle=2026536
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:119)
at android.os.Looper.loop(Looper.java:117)
at android.os.HandlerThread.run(HandlerThread.java:60)

"WebViewCoreThread" prio=5 tid=8 SUSPENDED
| group="main" sCount=1 dsCount=0 obj=0x40547cf0 self=0x1a76f8
| sysTid=21618 nice=0 sched=0/0 cgrp=default handle=1734704
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:119)
at android.os.Looper.loop(Looper.java:117)
at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:685)
at java.lang.Thread.run(Thread.java:1019)

"Binder Thread #2" prio=5 tid=7 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40514248 self=0x182cb0
| sysTid=21617 nice=0 sched=0/0 cgrp=default handle=1427792
at dalvik.system.NativeStart.run(Native Method)

"Binder Thread #1" prio=5 tid=6 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40514180 self=0x15c6b0
| sysTid=21616 nice=0 sched=0/0 cgrp=default handle=1479520
at dalvik.system.NativeStart.run(Native Method)

"Compiler" daemon prio=5 tid=5 VMWAIT
| group="system" sCount=1 dsCount=0 obj=0x40510d68 self=0x163270
| sysTid=21615 nice=0 sched=0/0 cgrp=default handle=1454640
at dalvik.system.NativeStart.run(Native Method)

"Signal Catcher" daemon prio=5 tid=4 RUNNABLE
| group="system" sCount=0 dsCount=0 obj=0x40510ca8 self=0x97570
| sysTid=21614 nice=0 sched=0/0 cgrp=default handle=619824
at dalvik.system.NativeStart.run(Native Method)

"GC" daemon prio=5 tid=3 VMWAIT
| group="system" sCount=1 dsCount=0 obj=0x40510c00 self=0x96e08
| sysTid=21613 nice=0 sched=0/0 cgrp=default handle=617928
at dalvik.system.NativeStart.run(Native Method)

"HeapWorker" daemon prio=5 tid=2 VMWAIT
| group="system" sCount=1 dsCount=0 obj=0x40510b48 self=0x162fb8
| sysTid=21612 nice=0 sched=0/0 cgrp=default handle=617728
at dalvik.system.NativeStart.run(Native Method)
```

Original comment by `flik...@gmail.com` on 29 Dec 2012 at 11:57
