### ISSUE TITLE
[audible][0.4.1] java.lang.NullPointerException in com.softenido.cafedroid.e.k.b

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#40]
```
java.lang.NullPointerException
at com.softenido.cafedroid.e.k.b(Unknown Source)
at com.softenido.cafedroid.e.k.a(Unknown Source)
at com.softenido.cafedroid.e.k.d(Unknown Source)
at com.softenido.cafedroid.e.c.m(Unknown Source)
at com.softenido.cafedroid.e.c.a(Unknown Source)
at com.softenido.cafedroid.e.d.run(Unknown Source)
at java.lang.Thread.run(Thread.java:1019)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 29 Dec 2012 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
retraced:

java.lang.NullPointerException
at com.softenido.cafedroid.speech.SpeechSpeaker.void install()(Unknown Source)
                                                int isLanguageAvailable(java.util.Locale)
                                                void unregisterOnSpeakingListener(com.softenido.cafedroid.speech.SpeechSpeaker$OnSpeakingListener)
                                                void adjustVolume(int,int)
at com.softenido.cafedroid.speech.SpeechSpeaker.boolean start()(Unknown Source)
                                                void onActivityResult(int,int,android.content.Intent)
                                                int setLanguage(java.util.Locale)
                                                boolean waitForStarted(int)
                                                java.util.Locale[] getAvailableLocales(java.util.Locale[])
                                                java.lang.String speak(java.lang.String,boolean,boolean)
                                                java.lang.String speak(java.lang.String,boolean,boolean,java.lang.String)
                                                void registerOnSpeakingListener(com.softenido.cafedroid.speech.SpeechSpeaker$OnSpeakingListener)
                                                void setVolume(int,int)
at com.softenido.cafedroid.speech.SpeechSpeaker.java.util.Locale[] 
getAvailableLocales()(Unknown Source)
at com.softenido.cafedroid.speech.SpeechPlayer.void speak()(Unknown Source)
at com.softenido.cafedroid.speech.SpeechPlayer.void 
setLocale(java.lang.String,java.lang.String)(Unknown Source)
                                               java.util.Locale getLocaleFor(java.lang.String)
                                               void waitFor(java.lang.String[][],int)
                                               void waitFor(java.lang.String[][],int,int)
                                               void seek(boolean,boolean)
                                               boolean play()
                                               void prev(boolean)
                                               void registerOnStatusChangedListener(com.softenido.cafedroid.speech.SpeechPlayer$OnStatusChangedListener)
                                               void setView(com.softenido.cafecore.gauge.GaugeView)
                                               void setWakeLock(android.os.PowerManager$WakeLock)
                                               void setVolume(int,int)
                                               boolean set(java.lang.String[])
                                               boolean setMark(com.softenido.cafedroid.speech.SpeechPlayer$Mark)
                                               void access$000(com.softenido.cafedroid.speech.SpeechPlayer)
at com.softenido.cafedroid.speech.SpeechPlayer$1.void run()(Unknown Source)
at java.lang.Thread.run(Thread.java:1019)
```

Original comment by `flik...@gmail.com` on 29 Dec 2012 at 3:10
