### ISSUE TITLE
[audible][0.5.0] java.lang.NullPointerException in com.softenido.a.g.b.a

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#41]
```
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.softenido.audible/com.softenido.audible.AudibleMain}: 
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1659)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
at android.app.ActivityThread.access$1500(ActivityThread.java:121)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:138)
at android.app.ActivityThread.main(ActivityThread.java:3701)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.softenido.a.g.b.a(Unknown Source)
at com.softenido.audible.AudibleMain.b(Unknown Source)
at com.softenido.audible.AudibleMain.onCreate(Unknown Source)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
... 11 more
```

Original issue reported on code.google.com by `flik...@gmail.com` on 6 Jan 2013 at 4:32

**Comment by GoogleCodeExporter** [comment]
```
retraced:

java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.softenido.audible/com.softenido.audible.AudibleMain}: 
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1659)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
at android.app.ActivityThread.access$1500(ActivityThread.java:121)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:138)
at android.app.ActivityThread.main(ActivityThread.java:3701)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.softenido.cafecore.text.Paragraphs.java.lang.String[] 
split(java.lang.String,boolean)(Unknown Source)
at com.softenido.audible.AudibleMain.void 
setTitleAndText(java.lang.String,java.lang.String)(Unknown Source)
                                     void setStatus(com.softenido.audible.AudibleMain$Status)
                                     void onStatusPlay()
                                     void adjustVolume(int)
                                     void loadTextFile(android.net.Uri)
                                     void access$400(com.softenido.audible.AudibleMain)
                                     void access$1200(com.softenido.audible.AudibleMain,com.softenido.audible.AudibleMain$Status)
at com.softenido.audible.AudibleMain.void onCreate(android.os.Bundle)(Unknown 
Source)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
... 11 more


```

Original comment by `flik...@gmail.com` on 6 Jan 2013 at 4:33
