### ISSUE TITLE
[audible][0.5.1]java.lang.IllegalArgumentException in java.lang.Enum.valueOf

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#42]
```
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.softenido.audible/com.softenido.audible.AudibleMain}: 
java.lang.IllegalArgumentException: PORTRAİT is not a constant in 
com.softenido.audible.ae
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$600(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5485)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: PORTRAİT is not a constant in 
com.softenido.audible.ae
at java.lang.Enum.valueOf(Enum.java:192)
at com.softenido.audible.ae.valueOf(Unknown Source)
at com.softenido.audible.AudibleMain.v(Unknown Source)
at com.softenido.audible.AudibleMain.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:5066)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
... 11 more
```

Original issue reported on code.google.com by `flik...@gmail.com` on 15 Jan 2013 at 10:10

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Retraced:

java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.softenido.audible/com.softenido.audible.AudibleMain}: 
java.lang.IllegalArgumentException: PORTRAİT is not a constant in 
com.softenido.audible.ae
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$600(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5485)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: PORTRAİT is not a constant in 
com.softenido.audible.ae
at java.lang.Enum.valueOf(Enum.java:192)
at 
com.softenido.audible.AudibleMain$ScreenOrientation.com.softenido.audible.Audibl
eMain$ScreenOrientation valueOf(java.lang.String)(Unknown Source)
at 
com.softenido.audible.AudibleMain.com.softenido.audible.AudibleMain$ScreenOrient
ation getOrientation()(Unknown Source)
at com.softenido.audible.AudibleMain.void onCreate(android.os.Bundle)(Unknown 
Source)
at android.app.Activity.performCreate(Activity.java:5066)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
... 11 more

```

Original comment by `flik...@gmail.com` on 15 Jan 2013 at 10:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `flik...@gmail.com` on 15 Jan 2013 at 10:20
- Changed state: **Started**
