### ISSUE TITLE
[audible][0.5.1] java.lang.NullPointerException in com.softenido.cafedroid.e.k.a

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#45]
```
java.lang.NullPointerException
at com.softenido.cafedroid.e.k.a(Unknown Source)
at com.softenido.cafedroid.e.c.m(Unknown Source)
at com.softenido.cafedroid.e.c.a(Unknown Source)
at com.softenido.cafedroid.e.d.run(Unknown Source)
at java.lang.Thread.run(Thread.java:1052)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 29 Jan 2013 at 9:36

**Comment by GoogleCodeExporter** [comment]
```
Retraced:

java.lang.NullPointerException
at com.softenido.cafedroid.speech.SpeechSpeaker.boolean start()(Unknown Source)
                                                void onActivityResult(int,int,android.content.Intent)
                                                int setLanguage(java.util.Locale)
                                                boolean waitForStarted(int)
                                                java.lang.String speak(java.lang.String,boolean,boolean)
                                                java.lang.String speak(java.lang.String,boolean,boolean,java.lang.String)
                                                void registerOnSpeakingListener(com.softenido.cafedroid.speech.SpeechSpeaker$OnSpeakingListener)
                                                void setVolume(int,int)
at com.softenido.cafedroid.speech.SpeechPlayer.void speak()(Unknown Source)
at com.softenido.cafedroid.speech.SpeechPlayer.void 
setLocale(java.lang.String,java.lang.String)(Unknown Source)
                                               java.util.Locale getLocaleFor(java.lang.String)
                                               void waitFor(java.lang.String[][],int)
                                               void waitFor(java.lang.String[][],int,int)
                                               void seek(boolean,boolean)
                                               boolean play()
                                               void prev(boolean)
                                               void registerOnStatusChangedListener(com.softenido.cafedroid.speech.SpeechPlayer$OnStatusChangedListener)
                                               void setView(com.softenido.cafecore.gauge.GaugeView)
                                               void setWakeLock(android.os.PowerManager$WakeLock)
                                               void setVolume(int,int)
                                               boolean set(java.lang.String[])
                                               boolean setMark(com.softenido.cafedroid.speech.SpeechPlayer$Mark)
                                               com.softenido.cafedroid.speech.SpeechPlayer$Mark buildMark(double,boolean,boolean)
                                               void access$000(com.softenido.cafedroid.speech.SpeechPlayer)
at com.softenido.cafedroid.speech.SpeechPlayer$1.void run()(Unknown Source)
at java.lang.Thread.run(Thread.java:1052)

```

Original comment by `flik...@gmail.com` on 29 Jan 2013 at 9:38
