### ISSUE TITLE
[audible][0.5.1] android.view.ViewRootImpl$CalledFromWrongThreadException in android.view.ViewRootImpl.checkThread

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#46]
```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original 
thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4264)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:750)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.setFlags(View.java:6750)
at android.view.View.setVisibility(View.java:4623)
at android.widget.ImageView.setVisibility(ImageView.java:1042)
at com.softenido.audible.AudibleMain.b(Unknown Source)
at com.softenido.audible.AudibleMain.a(Unknown Source)
at com.softenido.audible.AudibleMain.b(Unknown Source)
at com.softenido.cafedroid.e.c.n(Unknown Source)
at com.softenido.cafedroid.e.c.m(Unknown Source)
at com.softenido.cafedroid.e.c.a(Unknown Source)
at com.softenido.cafedroid.e.d.run(Unknown Source)
at java.lang.Thread.run(Thread.java:856)
```

Original issue reported on code.google.com by `flik...@gmail.com` on 29 Jan 2013 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original
thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4264)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:750)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.requestLayout(View.java:12725)
at android.view.View.setFlags(View.java:6750)
at android.view.View.setVisibility(View.java:4623)
at android.widget.ImageView.setVisibility(ImageView.java:1042)
at com.softenido.audible.AudibleMain.void 
setTitleAndText(java.lang.String,java.lang.String)(Unknown Source)
                                     void setStatus(com.softenido.audible.AudibleMain$Status)
                                     void onStatusPlay()
                                     void adjustVolume(int)
                                     void loadTextFile(android.net.Uri)
                                     void access$400(com.softenido.audible.AudibleMain)
                                     void access$1200(com.softenido.audible.AudibleMain,com.softenido.audible.AudibleMain$Status)
at com.softenido.audible.AudibleMain.com.softenido.cafedroid.util.ui.Notifier 
buildNotifier(boolean,boolean)(Unknown Source)
                                     boolean strictMode(boolean)
                                     void fixStatus(com.softenido.audible.AudibleMain$Status)
                                     void saveSettings()
                                     java.lang.String toString(java.lang.Object)
                                     void onStatusPlaying(int,int,java.util.Locale,java.lang.String)
                                     boolean isTitleRepeated(java.lang.String,java.lang.String)
                                     void setVolume(int)
                                     void loadHeadAndBody(android.net.Uri)
                                     void showSettings(java.lang.String)
                                     boolean setOrientation(com.softenido.audible.AudibleMain$ScreenOrientation)
                                     boolean access$002(com.softenido.audible.AudibleMain,boolean)
                                     void access$100(com.softenido.audible.AudibleMain,com.softenido.audible.AudibleMain$Status)
                                     void access$300(com.softenido.audible.AudibleMain)
                                     void access$500(com.softenido.audible.AudibleMain,java.lang.String)
                                     int access$1002(com.softenido.audible.AudibleMain,int)
                                     java.util.Locale access$1102(com.softenido.audible.AudibleMain,java.util.Locale)
                                     void access$1700(com.softenido.audible.AudibleMain,java.lang.String,java.lang.String)
at com.softenido.audible.AudibleMain.void 
setTitleAndText(java.lang.String,java.lang.String)(Unknown Source)
                                     void setStatus(com.softenido.audible.AudibleMain$Status)
                                     void onStatusPlay()
                                     void adjustVolume(int)
                                     void loadTextFile(android.net.Uri)
                                     void access$400(com.softenido.audible.AudibleMain)
                                     void access$1200(com.softenido.audible.AudibleMain,com.softenido.audible.AudibleMain$Status)
at com.softenido.cafedroid.speech.SpeechPlayer.void onStatusPlay()(Unknown 
Source)
at com.softenido.cafedroid.speech.SpeechPlayer.void speak()(Unknown Source)
at com.softenido.cafedroid.speech.SpeechPlayer.void 
setLocale(java.lang.String,java.lang.String)(Unknown Source)
                                               java.util.Locale getLocaleFor(java.lang.String)
                                               void waitFor(java.lang.String[][],int)
                                               void waitFor(java.lang.String[][],int,int)
                                               void seek(boolean,boolean)
                                               boolean play()
                                               void prev(boolean)
                                               void registerOnStatusChangedListener(com.softenido.cafedroid.speech.SpeechPlayer$OnStatusChangedListener)
                                               void setView(com.softenido.cafecore.gauge.GaugeView)
                                               void setWakeLock(android.os.PowerManager$WakeLock)
                                               void setVolume(int,int)
                                               boolean set(java.lang.String[])
                                               boolean setMark(com.softenido.cafedroid.speech.SpeechPlayer$Mark)
                                               com.softenido.cafedroid.speech.SpeechPlayer$Mark buildMark(double,boolean,boolean)
                                               void access$000(com.softenido.cafedroid.speech.SpeechPlayer)
at com.softenido.cafedroid.speech.SpeechPlayer$1.void run()(Unknown Source)
at java.lang.Thread.run(Thread.java:856)

```

Original comment by `flik...@gmail.com` on 29 Jan 2013 at 9:41
