### ISSUE TITLE
[audible][0.6.2] java.lang.NullPointerException in com.softenido.audible.AudibleMain.loadHeadAndBody

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jareens/softenido#48]
```
stack:
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.softenido.audible/com.softenido.audible.AudibleMain}: 
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1967)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
at android.app.ActivityThread.access$600(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4441)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.softenido.audible.AudibleMain.loadHeadAndBody(AudibleMain.java:682)
at com.softenido.audible.AudibleMain.onCreate(AudibleMain.java:275)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
... 11 more

message: hi error occured after i wanted to share selected text from web page 
with audible.
```

Original issue reported on code.google.com by `flik...@gmail.com` on 27 Feb 2013 at 9:08

**Comment by GoogleCodeExporter** [comment]
```
retraced:

java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.softenido.audible/com.softenido.audible.AudibleMain}: 
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1967)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
at android.app.ActivityThread.access$600(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4441)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.softenido.audible.AudibleMain.void 
loadHeadAndBody()(AudibleMain.java:682)
                                     void loadHeadAndBody(android.net.Uri)
at com.softenido.audible.AudibleMain.void 
onCreate(android.os.Bundle)(AudibleMain.java:275)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
... 11 more
```

Original comment by `flik...@gmail.com` on 27 Feb 2013 at 9:10
